FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# VUTTR

VUTTR é um simples repositório para gerenciar ferramentas com seus respectivos nomes, links, descrições e tags.

## Recursos do VUTTR [/tools]

### Listar Todas as Ferramentas [GET]

+ Response 200 (application/json)

        [
    {
        id: 1,
        title: "Notion",
        link: "https://notion.so",
        description: "All in one tool to organize teams and ideas. Write, plan, collaborate, and get organized. ",
        tags: [
            "organization",
            "planning",
            "collaboration",
            "writing",
            "calendar"
        ]
    },
    {
        id: 2,
        title: "json-server",
        link: "https://github.com/typicode/json-server",
        description: "Fake REST API based on a json schema. Useful for mocking and creating APIs for front-end devs to consume in coding challenges.",
        tags: [
            "api",
            "json",
            "schema",
            "node",
            "github",
            "rest"
        ]
    },
    {
        id: 3,
        title: "fastify",
        link: "https://www.fastify.io/",
        description: "Extremely fast and simple, low-overhead web framework for NodeJS. Supports HTTP2.",
        tags: [
            "web",
            "framework",
            "node",
            "http2",
            "https",
            "localhost"
        ]
    }
]

### Filtrar as Ferramentas com Busca por Tag [GET]
+ Parameters
    + tag: `node` (string)

+ Response 200 (application/json)

        [
    {
        id: 2,
        title: "json-server",
        link: "https://github.com/typicode/json-server",
        description: "Fake REST API based on a json schema. Useful for mocking and creating APIs for front-end devs to consume in coding challenges.",
        tags: [
            "api",
            "json",
            "schema",
            "node",
            "github",
            "rest"
        ]
    },
    {
        id: 3,
        title: "fastify",
        link: "https://www.fastify.io/",
        description: "Extremely fast and simple, low-overhead web framework for NodeJS. Supports HTTP2.",
        tags: [
            "web",
            "framework",
            "node",
            "http2",
            "https",
            "localhost"
        ]
    }
]

### Criar uma Nova Ferramenta [POST]

Você pode criar sua própria ferramenta usando esta ação.
É necessário enviar um objeto JSON contendo todas as informações da ferramenta.

+ Request (application/json)

        {
            "title": "hotel",
            "link": "https://github.com/typicode/hotel",
            "description": "Local app manager. Start apps within your browser, developer tool with local .localhost domain and https out of the box.",
            "tags":["node", "organizing", "webapps", "domain", "developer", "https", "proxy"]
        }

+ Response 200 (application/json)

    + Body

            {
                "title": "hotel",
                "link": "https://github.com/typicode/hotel",
                "description": "Local app manager. Start apps within your browser, developer tool with local .localhost domain and https out of the box.",
                "tags":["node", "organizing", "webapps", "domain", "developer", "https", "proxy"],
                "id":5
            }

### Remover uma Ferramenta [DELETE /tools/:id]

Você pode deletar suas ferramentas usando esta ação.
É necessário enviar o ID da ferramenta como parâmetro na URL.

+ Response 200 (application/json)

    Status: 200 OK
    {}